---

galaxy_info:
  author: charlesrocket
  description: Tasks for desktop targets
  role_name: desktop
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: FreeBSD
      versions:
        - all
  galaxy_tags:
    - desktop
    - workstation
